CREATE DATABASE selvox;

USE selvox;

CREATE TABLE Users (
	Id INT NOT NULL PRIMARY KEY,
	Username VARCHAR(100) NOT NULL,
	Email VARCHAR(150) NOT NULL,
	RoleId INT NOT NULL,
);

CREATE TABLE Roles (
	Id INT NOT NULL PRIMARY KEY,
	RoleType VARCHAR(50) NOT NULL,
);